name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: "ubuntu-22.04"

stages:
  - stage: deploy
    jobs:
      - job: deploy
        displayName: Deploy containers to dockerhub
        variables:
          - group: deployment-information
        steps:
          - task: Docker@2
            displayName: Login to docker hub
            inputs:
              command: login
              containerRegistry: dockerhub
          - task: Docker@2
            displayName: Login to chimera
            inputs:
              command: login
              containerRegistry: CHIMERA-U-ACR
          - script: |
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              if [[ "$TAG" == *stable* ]]; then export BUILD_TYPE=stable; else export BUILD_TYPE=latest; fi
              docker build --build-arg version=$TAG --build-arg branch=$BUILD_TYPE -t cccs/${BUILD_REPOSITORY_NAME##*/}:$TAG -t cccs/${BUILD_REPOSITORY_NAME##*/}:$BUILD_TYPE -f ./Dockerfile .
            workingDirectory: $(full_self_location)
            displayName: Build containers
          - script: |
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              if [[ "$TAG" == *stable* ]]; then export BUILD_TYPE=stable; else export BUILD_TYPE=latest; fi

              for IMAGE in "cccs/" "uchimera.azurecr.io/cccs/"
              do
                docker tag cccs/${BUILD_REPOSITORY_NAME##*/}:$BUILD_TYPE ${IMAGE}${BUILD_REPOSITORY_NAME##*/}:$TAG
                docker tag cccs/${BUILD_REPOSITORY_NAME##*/}:$BUILD_TYPE ${IMAGE}${BUILD_REPOSITORY_NAME##*/}:$BUILD_TYPE
                docker push ${IMAGE}${BUILD_REPOSITORY_NAME##*/} --all-tags
              done
            displayName: Deploy to Docker Hub
